name: Pygame Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Choose a Python version that is available
        architecture: x64  # Use x64 (64-bit) architecture

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygame

    - name: Run tests
      run: |
        python your_pygame_script.py
